const String SpSignUpSuccessMsg = 'تم انشاء الحساب بنجاح , يرجى تسجيل الدخول';
const String SpSignUpErrorMsg = 'خطأ في عملية التسجيل ';
const String SpSignUpLoadingMsg = 'جاري تسجيل طلبك , انتظر قليلا';
const String contactNumber = '+96171785528';

const Map<String, String> arabicSpecLikeInBackEnd = {
  'anxiety': 'القلق',
  'depression': 'الاكتئاب',
  'phobia': 'الرهاب',
  'obsession': 'الوسواس',
  'sexual disorder': 'اضطراب جنسي',
  'eating disorder': 'اضطراب الاكل',
  'Personality Disorder': 'اضطراب الشخص',
  'Borderline': 'حدي',
  'Narcissistic': 'نرجسي',
  'Obsessive': 'وسواس',
  'Dependant': 'اعتمادي',
  'Phobic': 'رهابي',
  'diagonally': 'انحرافي',
  'Addiction': 'الإدمان',
  'Traumatic Stress Disorder': 'اضطراب الصدمة',
  'Health Care': 'عناية صحية',
  'Sport System': 'نظام رياضي',
  'Dietary System': 'نظام غذائي',
  'Periodic Examinations': 'فحوص دورية',
  'Improving Trust': 'تحسين الثقة',
  'Achieving Goals': 'تحقيق الأهداف',
  'Achieving Success': 'تحقيق النجاح',
  'Dialectical Strategies': 'استراتيجيات جدلية حل',
  'Achieving Balance': 'تحقيق التوازن',
  'Relaxation': 'الاسترخاء',
  'Stress Management': 'تحمل الضغوط',
  'Emotional Control': 'ضبط المشاعر',
  'Rehabilitation and Support': 'اعادة تأهيل ودعم',
  'Psychological Prevention And Follow-Up': 'وقاية ومتابعة نفسية',
  'Children\'s Disorder': 'اضطرابات الأطفال',
  'Solve Problems': 'حل مشكلات',
  'Guidance and Instructions': 'إرشاد وتوجيه',
  'Psychological Disorders': 'اضطرابات نفسية',
  'Group Therapy': 'علاج جماعي',
  'Therapeutic Programs': 'برامج علاجية',
  'Anxiety': 'القلق',
  'Depression': 'الاكتئاب',
  'Phobia': 'الرهاب',
  'Obsessive-Compulsive Disorder': 'الوسواس',
  'Sexual Disorder': 'اضطراب جنسي',
  'Eating Disorder': 'اضطرابات الأكل',
  'Trauma Disorder': 'اضطراب الصدمة',
};
